/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#9e9d99',
        outline: '#787774',
        'secondary-fixed': '#d0e9d4',
        'on-primary-fixed-variant': '#611305',
        'on-tertiary-fixed': '#3c2800',
        'on-primary': '#ffefec',
        'surface-tint': '#9c3d2a',
        'on-error-container': '#510017',
        'tertiary-container': '#f7bd4f',
        'on-surface-variant': '#5c5b59',
        primary: '#9c3d2a',
        'on-secondary-fixed': '#2f4435',
        'on-error': '#ffefef',
        'on-tertiary-fixed-variant': '#624400',
        'primary-dim': '#8c3220',
        'tertiary-dim': '#6a4a00',
        'error-dim': '#a70138',
        'primary-container': '#fa846c',
        'on-tertiary': '#fff1df',
        'inverse-surface': '#0e0e0c',
        'on-surface': '#2f2f2c',
        'outline-variant': '#afada9',
        'primary-fixed': '#fa846c',
        'on-secondary-fixed-variant': '#4b6151',
        error: '#b41340',
        'surface': '#f9f6f2',
        secondary: '#4b6151',
        'secondary-dim': '#3f5445',
        'on-background': '#2f2f2c',
        'surface-container-low': '#f3f0ec',
        tertiary: '#795500',
        'surface-variant': '#dfddd8',
        'surface-dim': '#d6d4cf',
        'on-secondary-container': '#415747',
        'surface-container-highest': '#dfddd8',
        'on-secondary': '#e0f9e4',
        'surface-bright': '#f9f6f2',
        'tertiary-fixed-dim': '#e8af43',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#540900',
        'on-primary-fixed': '#160100',
        'surface-container-high': '#e5e2dd',
        'secondary-container': '#d0e9d4',
        'on-tertiary-container': '#563b00',
        'tertiary-fixed': '#f7bd4f',
        'error-container': '#f74b6d',
        'inverse-primary': '#fa846c',
        'primary-fixed-dim': '#e97860',
        background: '#f9f6f2',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
        label: ['Be Vietnam Pro', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
